services:
  - type: web
    name: messdienerplan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: IHR_SICHERES_ADMIN_PASSWORT_HIER
    plan: free
